FROM maildev/maildev:latest

# Maildev SMTP и Web интерфейс
EXPOSE 1025 1080

# Maildev запускается автоматически при старте контейнера
# Порт 1025 - SMTP сервер
# Порт 1080 - Web интерфейс для просмотра писем

